# Generated by Django 3.1.2 on 2020-10-15 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(null=True, to='blogApp.Tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='teams',
            field=models.ManyToManyField(null=True, to='blogApp.Team'),
        ),
        migrations.AddField(
            model_name='post',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogApp.theme'),
        ),
    ]
