# Generated by Django 3.1.2 on 2020-10-22 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogApp.conference'),
        ),
        migrations.AddField(
            model_name='team',
            name='defeats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogApp.division'),
        ),
        migrations.AddField(
            model_name='team',
            name='draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
