# Generated by Django 3.1.2 on 2020-10-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0007_auto_20201022_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='picture',
        ),
    ]
